sudo: required

services:
  - docker

language: java
jdk:
  - oraclejdk8

### whitelist
#branches:
#  only:
#    - master
#

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "cd edm-webapp"
  - "mvn package docker:build -DskipTests"
  - "cd -"
