sudo: false

language: java
jdk:
  - openjdk7
  - oraclejdk7
### whitelist
#branches:
#  only:
#    - master
#

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "cd edm-webapp"
  - "./node_modules/protractor/bin/webdriver-manager update"
  - "./node_modules/protractor/bin/webdriver-manager start &"
