sudo: required

services:
  - docker

language: java
jdk:
  - oraclejdk8

### whitelist
#branches:
#  only:
#    - master
#

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y tesseract-ocr

# build database and prepare for UI tests
before_script:
  - "cd docker_elastic_image/"
  - "make build"
  - "make drun"
  - "cd -"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "cd edm-webapp"
  - "mvn package docker:build -DskipTests"
  - "cd -"

after_script:
  - "cd docker_elastic_image/"
  - "make drm"
  - "cd -"

