sudo: required

services:
  - docker

language: java
jdk:
  - oraclejdk8

### whitelist
#branches:
#  only:
#    - master
#

# build database and prepare for UI tests
before_script:
  - "cd docker_elastic_image/"
  - "make build"
  - "docker run --name paperless-documents-search-db-test -d -p 9200:9200 -p 9300:9300 paperless-documents-search-db"
  - "cd -"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "cd edm-webapp"
  - "mvn package docker:build -DskipTests"
  - "cd -"

after_script:
  - "docker rm -f paperless-documents-search-db-test"

