sudo: required

services:
  - docker

addons:
  chrome: stable

language: java
jdk:
  - oraclejdk8

### whitelist
#branches:
#  only:
#    - master
#

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sudo apt-get -qq update
  - sudo apt-get install -y tesseract-ocr
  - npm install -g @angular/cli

# build database and prepare for UI tests
before_script:
  - "cd edm-elasticsearch-docker-image/"
  - "make drun"
  - "cd -"

after_script:
  - "cd edm-elasticsearch-docker-image/"
  - "make drm"
  - "cd -"

