version: '3'

services:

  loadbalancer:
    image: 'dockercloud/haproxy:latest'
    links:
      - webapp
    ports:
      - 8054:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web

  webapp:
    image: paperless-documents-search-webapp
    entrypoint: java -Dspring.profiles.active=prod -jar /webapp/paperless-documents-search-webapp.jar
    depends_on:
      - elasticsearch
    volumes:
      - /media/documents/Documents/:/media/documents:ro
    environment:
      - SPRING_APPLICATION_JSON={"spring.data.elasticsearch.cluster-nodes":"elasticsearch:9300"}
    networks:
      - web
      - back

  elasticsearch:
    image: paperless-documents-search-db
    ports:
      - 9200
      - 9300
    networks:
      - back

networks:
  web:
    driver: bridge
  back:
    driver: bridge

