version: '2'

services:

  paperless_documents_search_webapp:
    image: paperless-documents-search-webapp
    entrypoint: java -Dspring.profiles.active=local -jar /webapp/paperless-documents-search-webapp.jar
    ports:
      - 8053:8053
    depends_on:
      - paperless_documents_search_db
    volumes:
      - .:/host_mount_point
    environment:
      - spring.data.elasticsearch.cluster-nodes=paperless_documents_search_db:9300

  paperless_documents_search_db:
    image: paperless-documents-search-db
    ports:
      - 9200:9200
      - 9300:9300
